In [1]:
import pandas as pd
import numpy as np

from sklearn.metrics import roc_auc_score,accuracy_score

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [2]:
train = pd.read_csv('F://machine learning//Loan Prediction Problem//Loan Prediction Problem//train.csv')

In [3]:
train.head(5)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [4]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
Loan_ID              614 non-null object
Gender               601 non-null object
Married              611 non-null object
Dependents           599 non-null object
Education            614 non-null object
Self_Employed        582 non-null object
ApplicantIncome      614 non-null int64
CoapplicantIncome    614 non-null float64
LoanAmount           592 non-null float64
Loan_Amount_Term     600 non-null float64
Credit_History       564 non-null float64
Property_Area        614 non-null object
Loan_Status          614 non-null object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.4+ KB

In [5]:
train.isnull()   #Checking Missing Values

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,False,False,False,False,False,False,False,False,True,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,True,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,True,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,True,False,False,False,True,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False,False
23,False,True,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,True,False,False,False,False,True,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
584,False,False,False,False,False,False,False,False,False,False,False,False,False
585,False,False,False,False,False,False,False,False,False,False,False,False,False
586,False,False,False,False,False,False,False,False,False,False,False,False,False
587,False,False,False,False,False,False,False,False,False,False,False,False,False
588,False,True,False,False,False,False,False,False,False,False,False,False,False
589,False,False,False,False,False,False,False,False,False,False,False,False,False
590,False,False,False,False,False,False,False,False,False,False,False,False,False
591,False,False,False,False,False,False,False,False,False,False,False,False,False
592,False,True,False,False,False,False,False,False,False,False,False,False,False
593,False,False,False,False,False,False,False,False,False,False,False,False,False
594,False,False,False,False,False,False,False,False,False,False,False,False,False
595,False,False,False,False,False,False,False,False,False,False,False,False,False
596,False,False,False,False,False,False,False,False,False,False,False,False,False
597,False,False,False,True,False,False,False,False,False,False,False,False,False
598,False,False,False,False,False,False,False,False,False,False,False,False,False
599,False,False,False,False,False,False,False,False,False,False,False,False,False
600,False,False,False,False,False,True,False,False,False,False,True,False,False
601,False,False,False,False,False,True,False,False,False,False,False,False,False
602,False,False,False,False,False,False,False,False,False,False,False,False,False
603,False,False,False,False,False,False,False,False,False,False,False,False,False
604,False,False,False,False,False,False,False,False,False,False,False,False,False
605,False,False,False,False,False,False,False,False,True,False,False,False,False
606,False,False,False,False,False,False,False,False,False,False,False,False,False
607,False,False,False,False,False,False,False,False,False,False,False,False,False
608,False,False,False,False,False,False,False,False,False,False,False,False,False
609,False,False,False,False,False,False,False,False,False,False,False,False,False
610,False,False,False,False,False,False,False,False,False,False,False,False,False
611,False,False,False,False,False,False,False,False,False,False,False,False,False
612,False,False,False,False,False,False,False,False,False,False,False,False,False
613,False,False,False,False,False,False,False,False,False,False,False,False,False

In [6]:
train.isnull().sum()   #Finding the sum of all total null values

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [12]:
train.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [9]:
#now we will fill the missing values with mean and max values'

In [16]:

train.Gender.value_counts()
gender_cat = pd.get_dummies(train.Gender,prefix='gender').gender_Female

In [19]:
train.Married.value_counts()
married_category = pd.get_dummies(train.Married,prefix = 'marriage').marriage_Yes

In [21]:
train.Self_Employed.value_counts()
self_emp_category = pd.get_dummies(train.Self_Employed,prefix='employed').employed_Yes

In [22]:
train.Education.value_counts()
graduate_category = pd.get_dummies(train.Education,prefix='education').education_Graduate

In [24]:
loan_status = pd.get_dummies(train.Loan_Status,prefix='status').status_Y

In [26]:
property_category = pd.get_dummies(train.Property_Area,prefix='property')

In [30]:
train.shape

(614, 13)

In [28]:
#now we will fill the missing values with mean and max values'

In [33]:
train.Gender.fillna(train.Gender.max(),inplace =True)

TypeError: '>=' not supported between instances of 'str' and 'float'

In [34]:
train.Credit_History.fillna(train.Credit_History.max(),inplace=True)

In [35]:
train.LoanAmount.fillna(train.LoanAmount.mean(),inplace=True)

In [36]:
train.Loan_Amount_Term.fillna(train.Loan_Amount_Term.mean(),inplace=True)

In [37]:
train.Self_Employed.fillna(train.Self_Employed.max(),inplace=True)

TypeError: '>=' not supported between instances of 'str' and 'float'